package org.socraticgrid.hl7.services.ucs.accessclients.conversation;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was Originally generated by Apache CXF 2.7.8
 * Modified by Jerry Goodnough
 * 
 */
@WebServiceClient(name = "ConversationServiceService", 
                  wsdlLocation = "classpath:wsdl/ConversationService.wsdl",
                  targetNamespace = "org.socraticgrid.hl7.services.uc") 
public class ConversationServiceSE extends Service {

    public final static URL WSDL_LOCATION;

 

    public final static QName SERVICE = new QName("org.socraticgrid.hl7.services.uc", "ConversationServiceService");
    public final static QName ConversationServicePort = new QName("org.socraticgrid.hl7.services.uc", "conversationPort");
    
    static {
        URL url = null;
        url = ConversationServiceSE.class.getClassLoader().getResource("wsdl/ConversationService.wsdl");
        WSDL_LOCATION = url;
    }

    public ConversationServiceSE(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ConversationServiceSE(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConversationServiceSE() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ConversationServiceSE(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ConversationServiceSE(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ConversationServiceSE(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ConversationServiceSEI
     */
    @WebEndpoint(name = "conversationPort")
    public ConversationServiceSEI getConversationPort() {
        return super.getPort(ConversationServicePort, ConversationServiceSEI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConversationServiceSEI
     */
    @WebEndpoint(name = "conversationPort")
    public ConversationServiceSEI getConversationPort(WebServiceFeature... features) {
        return super.getPort(ConversationServicePort, ConversationServiceSEI.class, features);
    }

}
