package org.socraticgrid.hl7.services.ucs.accessclients.adapter;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was Originally generated by Apache CXF 2.7.8
 * Modified by Jerry Goodnough
 * 
 */
@WebServiceClient(name = "AdapterServiceService", 
                  wsdlLocation = "classpath:wsdl/AdapterService.wsdl",
                  targetNamespace = "org.socraticgrid.hl7.services.uc") 



public class AdapterServiceSE extends Service {

    public final static URL WSDL_LOCATION;

 

    public final static QName SERVICE = new QName("org.socraticgrid.hl7.services.uc", "AdapterServiceService");
    public final static QName AdapterServicePort = new QName("org.socraticgrid.hl7.services.uc", "adapterPort");
    
    static {
        URL url = null;
        url = AdapterServiceSE.class.getClassLoader().getResource("wsdl/AdapterService.wsdl");
        WSDL_LOCATION = url;
    }

    public AdapterServiceSE(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AdapterServiceSE(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AdapterServiceSE() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AdapterServiceSE(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AdapterServiceSE(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AdapterServiceSE(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ConversationServiceSEI
     */
    @WebEndpoint(name = "adapterPort")
    public AdapterServiceSEI getAdapterPort() {
        return super.getPort(AdapterServicePort, AdapterServiceSEI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConversationServiceSEI
     */
    @WebEndpoint(name = "adapterPort")
    public AdapterServiceSEI getAdapterPort(WebServiceFeature... features) {
        return super.getPort(AdapterServicePort, AdapterServiceSEI.class, features);
    }

}
