package org.socraticgrid.hl7.services.ucs.accessclients.ucsadapter;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was Originally generated by Apache CXF 2.7.8
 * Modified by Jerry Goodnough
 * 
 */
@WebServiceClient(name = "UCSAdapterServiceService", 
                  wsdlLocation = "classpath:UCSAdapterService.wsdl",
                  targetNamespace = "org.socraticgrid.hl7.services.uc.clients") 
public class UCSAdapterServiceSE extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("org.socraticgrid.hl7.services.uc.clients", "UCSAdapterServiceService");
    public final static QName UCSAdapterPort = new QName("org.socraticgrid.hl7.services.uc.clients", "ucsadapterPort");
    static {
        URL url = null;
        url = UCSAdapterServiceSE.class.getClassLoader().getResource("wsdl/UCSAdapterService.wsdl");
        WSDL_LOCATION = url;
    }

    public UCSAdapterServiceSE(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UCSAdapterServiceSE(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UCSAdapterServiceSE() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UCSAdapterServiceSE(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UCSAdapterServiceSE(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UCSAdapterServiceSE(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns UCSAdapterSEI
     */
    @WebEndpoint(name = "UCSAdapterPort")
    public UCSAdapterServiceSEI getUCSAdapterPort() {
        return super.getPort(UCSAdapterPort, UCSAdapterServiceSEI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Ucsclient
     */
    @WebEndpoint(name = "UCSAdapterPort")
    public UCSAdapterServiceSEI getUCSAdapterPort(WebServiceFeature... features) {
        return super.getPort(UCSAdapterPort, UCSAdapterServiceSEI.class, features);
    }

}
