DROP TABLE "UCOMM"."MESSAGE_JOIN_MESSAGE_BODY";
DROP TABLE "UCOMM"."MESSAGE_JOIN_PROCESSING_EXCEPTION";
DROP TABLE "UCOMM"."USER_CONTACT_INFO_JOIN_ADDRESS";
DROP TABLE "UCOMM"."CONVERSATION_JOIN_CONVERSATION_CHANNEL";
DROP TABLE "UCOMM"."CONVERSATION_JOIN_PARTICIPANT";
DROP TABLE "UCOMM"."MESSAGE_HEADER_ALERT_STATUS_JOIN_DELIVERY_ADDRESS";
DROP TABLE "UCOMM"."MESSAGE_HEADER_JOIN_DELIVERY_STATUS";
DROP TABLE "UCOMM"."MESSAGE_HEADER_JOIN_RECIPIENT";
DROP TABLE "UCOMM"."MESSAGE_HEADER_JOIN_SENDER";
DROP TABLE "UCOMM"."MESSAGE_JOIN_MESSAGE_BODY";
DROP TABLE "UCOMM"."MESSAGE_HEADER";
DROP TABLE "UCOMM"."CONVERSATION";
DROP TABLE "UCOMM"."CONVERSATION_CHANNEL";
DROP TABLE "UCOMM"."DELIVERY_STATUS";
DROP TABLE "UCOMM"."MESSAGE_BODY";
DROP TABLE "UCOMM"."USER_CONTACT_INFO";
DROP TABLE "UCOMM"."RECIPIENT";
DROP TABLE "UCOMM"."DELIVERY_ADDRESS";
DROP TABLE "UCOMM"."ADDRESS";
DROP TABLE "UCOMM"."PROCESSING_EXCEPTION";



DELETE FROM "UCOMM"."MESSAGE_JOIN_MESSAGE_BODY";
DELETE FROM "UCOMM"."MESSAGE_JOIN_PROCESSING_EXCEPTION";
DELETE FROM "UCOMM"."USER_CONTACT_INFO_JOIN_ADDRESS";
DELETE FROM "UCOMM"."CONVERSATION_JOIN_CONVERSATION_CHANNEL";
DELETE FROM "UCOMM"."CONVERSATION_JOIN_PARTICIPANT";
DELETE FROM "UCOMM"."MESSAGE_HEADER_ALERT_STATUS_JOIN_DELIVERY_ADDRESS";
DELETE FROM "UCOMM"."MESSAGE_HEADER_JOIN_DELIVERY_STATUS";
DELETE FROM "UCOMM"."MESSAGE_HEADER_JOIN_RECIPIENT";
DELETE FROM "UCOMM"."MESSAGE_JOIN_MESSAGE_BODY";
DELETE FROM "UCOMM"."MESSAGE_HEADER_JOIN_SENDER";
DELETE FROM "UCOMM"."MESSAGE_HEADER";
DELETE FROM "UCOMM"."CONVERSATION";
DELETE FROM "UCOMM"."CONVERSATION_CHANNEL";
DELETE FROM "UCOMM"."DELIVERY_STATUS";
DELETE FROM "UCOMM"."MESSAGE_BODY";
DELETE FROM "UCOMM"."USER_CONTACT_INFO";
DELETE FROM "UCOMM"."RECIPIENT";
DELETE FROM "UCOMM"."DELIVERY_ADDRESS";
DELETE FROM "UCOMM"."ADDRESS";
DELETE FROM "UCOMM"."PROCESSING_EXCEPTION";







