package org.socraticgrid.hl7.services.ucs.accessclients.ucsclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2014-01-31T11:31:08.102-08:00
 * Generated source version: 2.7.8
 * 
 *  "file:/C:/Users/Jerry%20Goodnough/.m2/repository/org/socraticgrid/hl7/UCSClient/0.0.3-SNAPSHOT/UCSClient-0.0.3-SNAPSHOT.wsdl"
 */
@WebServiceClient(name = "UCSClientServiceService", 
                  wsdlLocation = "classpath:UCSClient.wsdl",
                  targetNamespace = "org.socraticgrid.hl7.services.uc.clients") 
public class UCSClientServiceSE extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("org.socraticgrid.hl7.services.uc.clients", "UCSClientServiceService");
    public final static QName UcsclientPort = new QName("org.socraticgrid.hl7.services.uc.clients", "ucsclientPort");
    static {
        URL url = null;
        url = UCSClientServiceSE.class.getClassLoader().getResource("wsdl/UCSClient.wsdl");
        WSDL_LOCATION = url;
    }

    public UCSClientServiceSE(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UCSClientServiceSE(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UCSClientServiceSE() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UCSClientServiceSE(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UCSClientServiceSE(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UCSClientServiceSE(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns Ucsclient
     */
    @WebEndpoint(name = "ucsclientPort")
    public UCSClientServiceSEI getUcsclientPort() {
        return super.getPort(UcsclientPort, UCSClientServiceSEI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Ucsclient
     */
    @WebEndpoint(name = "ucsclientPort")
    public UCSClientServiceSEI getUcsclientPort(WebServiceFeature... features) {
        return super.getPort(UcsclientPort, UCSClientServiceSEI.class, features);
    }

}
