package org.socraticgrid.hl7.services.ucs.accessclients.ucsalerting;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was Originally generated by Apache CXF 2.7.8
 * Modified by Jerry Goodnough
 * 
 */
@WebServiceClient(name = "UCSAlertingServiceService", 
                  wsdlLocation = "classpath:UCSAlerting.wsdl",
                  targetNamespace = "org.socraticgrid.hl7.services.uc.clients") 
public class UCSAlertingServiceSE extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("org.socraticgrid.hl7.services.uc.clients", "UCSAlertingServiceService");
    public final static QName UcsalertingPort = new QName("org.socraticgrid.hl7.services.uc.clients", "ucsalertingPort");
    static {
        URL url = null;
        url = UCSAlertingServiceSE.class.getClassLoader().getResource("wsdl/UCSAlerting.wsdl");
        WSDL_LOCATION = url;
    }

    public UCSAlertingServiceSE(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UCSAlertingServiceSE(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UCSAlertingServiceSE() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UCSAlertingServiceSE(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UCSAlertingServiceSE(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UCSAlertingServiceSE(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns UcsAlertingSEI
     */
    @WebEndpoint(name = "ucsalertingPort")
    public UCSAlertingServiceSEI getUcsAlertingPort() {
        return super.getPort(UcsalertingPort, UCSAlertingServiceSEI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Ucsclient
     */
    @WebEndpoint(name = "ucsalertingPort")
    public UCSAlertingServiceSEI getUcsAlertingPort(WebServiceFeature... features) {
        return super.getPort(UcsalertingPort, UCSAlertingServiceSEI.class, features);
    }

}
