package org.socraticgrid.hl7.services.orders.accessclients.orderservice;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import org.socraticgrid.hl7.services.orders.interfaces.OrderManagementIFace;

/**
 * This class was Originally generated by Apache CXF 2.7.8
 * Modified by Jerry Goodnough
 * 
 */
@WebServiceClient(name = "OrderManagementServiceService", 
                  wsdlLocation = "classpath:wsdl/OrderManagementService.wsdl",
                  targetNamespace = "org.socraticgrid.hl7.services.orders") 
public class OrderManagementServiceSE extends Service {

    public final static URL WSDL_LOCATION;

 

    public final static QName SERVICE = new QName("org.socraticgrid.hl7.services.orders", "OrderManagementServiceService");
    public final static QName OrderManagementPort = new QName("org.socraticgrid.hl7.services.orders", "ordermanagementPort");
    
    static {
        URL url = null;
        url = OrderManagementServiceSE.class.getClassLoader().getResource("wsdl/OrderManagementService.wsdl");
        WSDL_LOCATION = url;
    }

    public OrderManagementServiceSE(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OrderManagementServiceSE(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrderManagementServiceSE() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OrderManagementServiceSE(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OrderManagementServiceSE(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OrderManagementServiceSE(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns OrderManagementIFace
     */
    @WebEndpoint(name = "ordermanagementPort")
    public OrderManagementIFace getOrderManagementPort() {
        return super.getPort(OrderManagementPort, OrderManagementIFace.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderManagementIFace
     */
    @WebEndpoint(name = "ordermanagementPort")
    public OrderManagementIFace getOrderManagementPort(WebServiceFeature... features) {
        return super.getPort(OrderManagementPort, OrderManagementIFace.class, features);
    }

}
