package org.socraticgrid.hl7.services.orders.accessclients.orderservice;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import org.socraticgrid.hl7.services.orders.interfaces.OrderMonitoringIFace;

/**
 * This class was Originally generated by Apache CXF 2.7.8
 * Modified by Jerry Goodnough
 * 
 */
@WebServiceClient(name = "OrderMonitoringServiceService", 
                  wsdlLocation = "classpath:wsdl/OrderMonitoringService.wsdl",
                  targetNamespace = "org.socraticgrid.hl7.services.orders") 
public class OrderMonitoringServiceSE extends Service {

    public final static URL WSDL_LOCATION;

 

    public final static QName SERVICE = new QName("org.socraticgrid.hl7.services.orders", "OrderMonitoringServiceService");
    public final static QName OrderMonitoringPort = new QName("org.socraticgrid.hl7.services.orders", "ordermonitoringPort");
    
    static {
        URL url = null;
        url = OrderMonitoringServiceSE.class.getClassLoader().getResource("wsdl/OrderMonitoringService.wsdl");
        WSDL_LOCATION = url;
    }

    public OrderMonitoringServiceSE(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OrderMonitoringServiceSE(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrderMonitoringServiceSE() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OrderMonitoringServiceSE(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OrderMonitoringServiceSE(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OrderMonitoringServiceSE(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns OrderMonitoringIFace
     */
    @WebEndpoint(name = "ordermonitoringPort")
    public OrderMonitoringIFace getOrderMonitoringPort() {
        return super.getPort(OrderMonitoringPort, OrderMonitoringIFace.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderMonitoringIFace
     */
    @WebEndpoint(name = "ordermonitoringPort")
    public OrderMonitoringIFace getOrderMonitoringPort(WebServiceFeature... features) {
        return super.getPort(OrderMonitoringPort, OrderMonitoringIFace.class, features);
    }

}
