package org.socraticgrid.hl7.services.eps.accessclients.brokermanagement;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import org.socraticgrid.hl7.services.eps.interfaces.BrokerManagementIFace;

/**
 * This class was Originally generated by Apache CXF 2.7.8
 * Modified by Jerry Goodnough
 * 
 */
@WebServiceClient(name = "BrokerManagementServiceService", 
                  wsdlLocation = "classpath:wsdl/BrokerManagementService.wsdl",
                  targetNamespace = "org.socraticgrid.hl7.services.eps") 
public class BrokerManagementServiceSE extends Service {

    public final static URL WSDL_LOCATION;

 

    public final static QName SERVICE = new QName("org.socraticgrid.hl7.services.eps", "BrokerManagementServiceService");
    public final static QName BrokerManagementServicePort = new QName("org.socraticgrid.hl7.services.eps", "brokermanagementPort");
    
    static {
        URL url = null;
        url = BrokerManagementServiceSE.class.getClassLoader().getResource("wsdl/BrokerManagementService.wsdl");
        WSDL_LOCATION = url;
    }

    public BrokerManagementServiceSE(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BrokerManagementServiceSE(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BrokerManagementServiceSE() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BrokerManagementServiceSE(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BrokerManagementServiceSE(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BrokerManagementServiceSE(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns TopicManagementServiceSEI
     */
    @WebEndpoint(name = "brokermanagementPort")
    public BrokerManagementIFace getBrokerManagementPort() {
        return super.getPort(BrokerManagementServicePort, BrokerManagementIFace.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TopicManagementServiceSEI
     */
    @WebEndpoint(name = "brokermanagementPort")
    public BrokerManagementIFace getBrokerManagementPort(WebServiceFeature... features) {
        return super.getPort(BrokerManagementServicePort, BrokerManagementIFace.class, features);
    }

}
